// Map Reducer Actions
export const DRAW_BOX = 'DRAW_BOX'
export const DRAW_POLY = 'DRAW_POLY'
export const MEASURE_DISTANCE = 'MEASURE_DISTANCE'
export const NONE = 'NONE'
export const PUSH_POSITION = 'PUSH_POSITION'
export const MAIN = 'MAIN'
export const PROOF = 'PROOF'
export const FETCH_POSITION_START = 'FETCH_POSITION_START'
export const FETCH_POSITION_STOP = 'FETCH_POSITION_STOP'
export const RECORD_POSITION_START = 'RECORD_POSITION_START'
export const RECORD_POSITION_STOP = 'RECORD_POSITION_STOP'
export const CURRENT_POSITION_UPDATE = 'CURRENT_POSITION_UPDATE'

// User Bound Actions
export const USER_BOUND_UPDATE_ON_ZOOM = 'USER_BOUND_UPDATE_ON_ZOOM'
export const USER_BOUND_UPDATE_ON_MOVE = 'USER_BOUND_UPDATE_ON_MOVE'

// Buffered Extents 
export const BUFFERED_EXTENTS_INITIALIZE =
  'BUFFERED_EXTENTS_INITIALIZE'
export const BUFFERED_EXTENTS_UPDATE_ON_NO_INTERSECTIONS =
  'BUFFERED_EXTENTS_UPDATE_ON_NO_INTERSECTIONS'
export const BUFFERED_EXTENTS_UPDATE_ON_ONE_INTERSECTIONS =
  'BUFFERED_EXTENTS_UPDATE_ON_ONE_INTERSECTIONS'
export const BUFFERED_EXTENTS_UPDATE_ON_TWO_INTERSECTIONS =
  'BUFFERED_EXTENTS_UPDATE_ON_TWO_INTERSECTIONS'
export const BUFFERED_EXTENTS_UPDATE_ON_THREE_INTERSECTIONS =
  'BUFFERED_EXTENTS_UPDATE_ON_THREE_INTERSECTIONS'
export const BUFFERED_EXTENTS_REMOVE_FURTHEST = 'BUFFERED_EXTENTS_REMOVE_FURTHEST'
export const BUFFERED_EXTENTS_NO_UPDATE = 'BUFFERED_EXTENTS_NO_UPDATE'

// Cached Data
export const CACHED_DATA_UPDATE = 'CACHED_DATA_UPDATE'
